version: "3.9"
services:
  app:
    image: myserv
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"